# Generated by Django 3.2.9 on 2021-12-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('frist_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_number', models.PositiveIntegerField(max_length=15)),
                ('email_id', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
