# Generated by Django 4.0 on 2021-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact_number',
            field=models.PositiveIntegerField(),
        ),
    ]
