# Generated by Django 4.0 on 2021-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_first_name_registration_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='First_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
