# Generated by Django 4.0 on 2021-12-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_first_name_registration_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
