# Generated by Django 4.0 on 2021-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
