# Generated by Django 4.0 on 2021-12-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_registration_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='contact_number',
            new_name='mobile',
        ),
    ]
