# Generated by Django 4.0 on 2022-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
